# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Promote Version

jobs:
  promote:
    name: Promoting to newer version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: maks-stupak/gh-action-bump-version@v7.1.5
        with:
            tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  